### PR TITLE
Handle cases when unknown metadataPrefix is received

### PR DESCRIPTION
**Pull request by cgendreau**
Handling of cases when ListIdentifiers or ListRecords request includes an unknown metadata prefix.

### CODE REVIEW

**Comment by mmalmeida** [comment]
Hi @cgendreau. 
I've recently been allocated to XOAI and I am currently reviewing the Pull requests.

While everything seems to be working in your change, the copy-paste of the same code in two classes violates the DRY principle.

Would you be able to refactor your commit as to not repeat the same code?

Thank you for your contribution!

**Comment by cgendreau** [comment]
Are you refering to ListIdentifiersHandler.java
and ListRecordsHandler.java or the test?

**Comment by mmalmeida** [comment]
I was referring to the Handlers (although you are right that the same thing could apply to the tests ;) )

**Comment by mmalmeida** [comment]
@cgendreau would you be able to provide the requested changes in time for the next release? Thanks!

**Comment by cgendreau** [comment]
yes, but I must admit I'm not sure what you expect.
This is a 3 lines precondition check that is not a good fit for `VerbHandler` or `ItemRepositoryHelper`.
Maybe a new `PreconditionHelper` under the `handlers` package?

**Comment by mmalmeida** [comment]
I agree. Handlers already has a helpers package, seems like a good place to put it.
Thanks!

**Pull request merged**
